spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labTest?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: zero81
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update